
###
POST http://localhost:3001/v1/auth/signup
Content-Type: application/json

{
    "password": "admintest1",
    "username": "admintest1",
    "name": "ADMIN TEST",
    "email": "admin@gmail.com",
    "phoneNumber": "0123456789",
    "role": "Quản trị viên"
}

###

POST https://3939-2402-9d80-c02-d6e6-ec68-4f62-3e24-658.ngrok-free.app/v1/auth/login
Content-Type: application/json

{
    "password": "studenttest1",
    "username": "studenttest1"
}

###

POST http://localhost:3000/v1/auth/login_test
Content-Type: application/json

{
    "password": "studenttest1",
    "username": "studenttest1"
}

###

GET http://localhost:3000/v1/user/search/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6Ikjhu41jIHZpw6puIiwiaWF0IjoxNzMyMzg0NzMwLCJleHAiOjE3MzI0Mjc5MzB9.Ho6Z5pAWybIgs3YI2-PovPiQyWSrFXR7a-7KU-gPnGI

{
    
}


###
POST http://localhost:3000/v1/auth/signup
Content-Type: application/json

{
    "password": "admintest1",
    "username": "admintest1",
    "name": "ADMIN TEST",
    "email": "admin1@gmail.com",
    "phoneNumber": "0123456789",
    "role": "Quản trị viên"
}