
###
POST http://localhost:3000/v1/user/search
Content-Type: application/json

{
    "criteria": [
        {
            "field": "ssoId",
            "operator": "=",
            "value": 1
        }
    ],
    "addition": ""
}



###
POST http://localhost:3000/v1/user/search
Content-Type: application/json

{
    "criteria": [
        {
            "field": "Student.ssoId",
            "operator": "=",
            "value": 1
        }
    ],
    "addition": ""
}


###
GET http://localhost:3000/v1/user/paper/search/1
Content-Type: application/json

{
    
}

###
GET http://localhost:3000/v1/user/admin/count/
Content-Type: application/json

{
    
}

