POST http://localhost:3001/v1/payment/create
Content-Type: application/json

{
    "studentId": 1,
    "comboType": "type1",
    "numberCombo": 1
}

###


GET http://localhost:3000/v1/payment/search
Content-Type: application/json

{
    
}

###


GET http://localhost:3000/v1/payment/search/student/1
Content-Type: application/json

{
    
}